spring:
  application:
    name: cloud-gateway-demo

server:
  port: 7300

eureka:
  client:
    service-url:
      defaultZone:
          http://young:123456@localhost:7000/eureka/

zuul:
  routes:
    cloud-api-demo: /api/**
    cloud-service-demo: /service/**
  retryable: true
#ribbon
#全局配置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1500

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
